### ISSUE TITLE
Video uploader - tried uploading image

### ISSUE THREAD

**Issue by taylorcc33** [dani7beth/MAP#91]
Tried uploading an image and received an infinite loading animation. Should probably through an error instead?
<img width="706" alt="Screen Shot 2021-02-01 at 11 51 57 AM" src="https://user-images.githubusercontent.com/13341676/106504318-03f85880-6484-11eb-8409-8604d342d830.png">

**Comment by dani7beth** [comment]
Error handling fixed on submissions and other uploaders.
